version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - lsdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - stack.env
  web:
    build:
      context: ./linkshortner
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - stack.env
    depends_on:
      - db

volumes:
  lsdata:
