# Generated by Django 5.0 on 2023-12-24 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('shortsvc', '0001_initial'), ('shortsvc', '0002_remove_shortenedlink_user_id_and_more'), ('shortsvc', '0003_shortenedlink_shorturl_alter_shortenedlink_id'), ('shortsvc', '0004_alter_shortenedlink_id'), ('shortsvc', '0005_shortenedlink_shortened_url_idx_and_more'), ('shortsvc', '0006_remove_shortenedlink_shortened_url_and_more'), ('shortsvc', '0007_urlsequence'), ('shortsvc', '0008_alter_shortenedlink_created_by')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_url', models.TextField()),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('shorturl', models.CharField(default='', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['shorturl'], name='shortened_url_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shortenedlink',
            constraint=models.UniqueConstraint(fields=('shorturl',), name='Shortened Url'),
        ),
        migrations.AlterModelTable(
            name='shortenedlink',
            table='shortenedlinks',
        ),
        migrations.RemoveConstraint(
            model_name='shortenedlink',
            name='Shortened Url',
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='shorturl',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='UrlSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
