# Generated by Django 5.0 on 2023-12-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortsvc', '0002_remove_shortenedlink_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedlink',
            name='shorturl',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
