# Generated by Django 5.0 on 2023-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortsvc', '0003_shortenedlink_shorturl_alter_shortenedlink_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
