# Generated by Django 5.0 on 2023-12-23 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortsvc', '0004_alter_shortenedlink_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shortenedlink',
            index=models.Index(fields=['shorturl'], name='shortened_url_idx'),
        ),
        migrations.AddConstraint(
            model_name='shortenedlink',
            constraint=models.UniqueConstraint(fields=('shorturl',), name='Shortened Url'),
        ),
        migrations.AlterModelTable(
            name='shortenedlink',
            table='shortenedlinks',
        ),
    ]
